<!DOCTYPE html>
<html>
<head>
    <title>PDF Example</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; }
    </style>
</head>
<body>
    <h1>Hello from PDF Example!</h1>
    <p>This is a PDF generated by Laravel DOMPDF.</p>
</body>
</html>
